# Generated by Django 5.1.4 on 2025-08-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_merge_20250802_0849'),
        ('students', '0002_alter_student_address_alter_studentattendance_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(related_name='enrolled_students', to='courses.courseoffering'),
        ),
    ]
