# Generated by Django 5.2.4 on 2025-08-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
