# Generated by Django 5.1.4 on 2025-08-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_scores_to_enrollment'),
        ('courses', '0002_alter_course_description'),
    ]

    operations = [
    ]
