# Generated by Django 5.2.4 on 2025-08-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_department_description'),
        ('courses', '0003_merge_20250802_0849'),
        ('students', '0003_student_enrolled_courses'),
        ('teachers', '0002_alter_teacher_address_alter_teacherattendance_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('W', 'Withdrawn'), ('I', 'Incomplete')], db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='withdrawn',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='courses_cou_code_612388_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='courses_cou_name_eb4cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department', 'credits'], name='courses_cou_departm_5073c7_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['semester', 'is_active'], name='courses_cou_semeste_ccbbd4_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['course', 'semester'], name='courses_cou_course__2f86cd_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'withdrawn'], name='courses_enr_student_ea8804_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course_offering', 'withdrawn'], name='courses_enr_course__82edfb_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['grade'], name='courses_enr_grade_17f4a5_idx'),
        ),
    ]
