# Generated by Django 5.2.4 on 2025-08-05 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_code_alter_course_credits_and_more'),
        ('teachers', '0002_alter_teacher_address_alter_teacherattendance_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_courses', to='teachers.teacher'),
        ),
    ]
