# Generated by Django 5.1.4 on 2025-08-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courseoffering_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='material',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
